
pipeline{
		agent any 
		stages {
			stage('Build Application'){
				steps {
				// Define  pom.xml file path 
					sh 'mvn -f java-tomcat-sample/pom.xml clean package'
					}
					post {
					success {
						echo "Now Archiving the Artifacts ..."
						archiveArtifacts artifacts: '**/*.war'
						}
					}
				}
			}
		}		


